#HTTP Port
quarkus.http.port=8080

# Reactive postgresql datasource
quarkus.datasource.db-kind=postgresql

# Either rely on Dev Services in dev/test (auto-provisions postgresql in a container)
#quarkus.datasource.devservices.enabled=true
# or configure a real postgresql instance (recommended for prod)
# Format: postgresql://HOST:PORT/DB
# Username/password are required when not using Dev Services
# Note: Hibernate Reactive uses the reactive URL (no jdbc:)
quarkus.datasource.reactive.url=postgresql://localhost:5433/e_com_crud_app
quarkus.datasource.username=postgres
quarkus.datasource.password=8143

#Hibernate Reactive settings
quarkus.hibernate-orm.database.generation=create
# Use drop-and-create for quick local prototyping:
quarkus.hibernate-orm.log.sql=true


#openAPI/Swagger UI
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.always-include=true


#log files
quarkus.log.console.enable=true
quarkus.log.file.enable=true
quarkus.log.file.path=logs/e_com_crud_app_logs.log
quarkus.log.level=INFO

